## Starting of Pandas

#### Pandas is a powerful, open-source Python library used for data manipulation, cleaning, and analysis. It provides two main data structures:

- Series: A one-dimensional labeled array
- DataFrame: A two-dimensional labeled table (like an Excel sheet or SQL table)

In [2]:
import pandas as pd

#### Series — 1D Labeled Array

In [3]:
s = pd.Series([1,2,3,4,5])

In [4]:
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

#### It gives the auto index

### DataFrame — 2D Labeled Table

In [5]:
data = {
    "Name" : ["Nikk","bob","ram"],
    "age" : [25,46,78],
    "city" : ["delhi","ktm","baneshwor"]
}

In [6]:
df = pd.DataFrame(data)

In [7]:
df

   Name  age       city
0  Nikk   25      delhi
1   bob   46        ktm
2   ram   78  baneshwor

#### Each column in a DataFrame is a Series.

In [8]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [9]:
df.columns

Index(['Name', 'age', 'city'], dtype='object')

In [10]:
df.index = ["a","b","c"]

In [11]:
df

   Name  age       city
a  Nikk   25      delhi
b   bob   46        ktm
c   ram   78  baneshwor

- Series = 1D array with labels
- DataFrame = 2D table with rows + columns